language: python
sudo: required
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      dist: xenial
      before_install: sudo apt-get install -y libusb-1.0-0-dev libudev-dev
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      env: PATH=/Users/travis/Library/Python/3.7/bin:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install: wget --progress=dot:mega https://bootstrap.pypa.io/get-pip.py &&
        choco install python --version 3.7.2 && python get-pip.py && rm get-pip.py && choco install nsis
      env: PATH=/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:$PATH
install:
  - pip3 install --user -r requirements.txt || pip3 install -r requirements.txt
  - pip3 install --user pyinstaller || pip3 install pyinstaller
script: pyinstaller specPet4l.spec
